[package]
name = "threaded_http"
version = "0.1.0"
edition = "2021"
authors = ["Mir Mohmmad Luqman"]
license = "MIT"
description = "A multithreaded HTTP server demonstrating Rust concurrency patterns"
repository = "https://github.com/mirmohmmadluqman/ThreadedHTTP"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4"

[dev-dependencies]
tempfile = "3.10"
